

demo:
  export-base-path: ./export

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:h2:mem:cmsmigration"
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
  batch:
    job:
      enabled: false

  thymeleaf:
    cache: false

com:
  namics:
    oss:
      spring:
        support:
          batch:
            job-configuration:
              package-name: com.example.batchdemo.jobs
#            web:
#              servlet-name: springBatch
#              servlet-mapping: /*
#              dark-mode: false
            clean-up:
              enabled: false
              keep-days: 20
              cron: "0/10 0/1 * 1/1 * ?"
